CREATE TABLE BOT_QUERY_CONFIG (
  ACCOUNT VARCHAR2(40),
  APPLICATION VARCHAR2(40),
  DB_UID VARCHAR2(40),
  DB_USER VARCHAR2(40),
  DB_PASS VARCHAR2(40),
  DB_URL VARCHAR2(4000),
  ALERT VARCHAR2(50),
  SQL_TXT VARCHAR2(4000),
  KEYWORD VARCHAR2(40),
  POST_INSTR VARCHAR2(2000),
  VERSION NUMBER,
  IS_ACTIVE VARCHAR2(1),
  CREATION_TIME TIMESTAMP,
  UPDATE_TIME TIMESTAMP,
  PRIMARY KEY (ALERT)
);

INSERT INTO BOT_QUERY_CONFIG(ACCOUNT, APPLICATION, DB_UID, DB_USER, DB_PASS, DB_URL, ALERT, SQL_TXT, KEYWORD,POST_INSTR,VERSION,IS_ACTIVE,CREATION_TIME, UPDATE_TIME)
VALUES ('test','test','local','rohitw','rohitw','jdbc:oracle:thin:@localhost:1521:rohitw','test alert','select * from TEST_DATA','test data','send email',1,'Y',sysdate,sysdate);

CREATE TABLE TEST_DATA (
  KEY VARCHAR2(40),
  VAL VARCHAR2(255),
  PRIMARY KEY (KEY)
);

grant all on BOT_QUERY_CONFIG to public;
grant all on TEST_DATA to public;
create public synonym BOT_QUERY_CONFIG for BOT_QUERY_CONFIG;
create public synonym TEST_DATA for TEST_DATA;

INSERT INTO TEST_DATA (KEY, VAL) VALUES ('FOO', 'BAR');
INSERT INTO TEST_DATA (KEY, VAL) VALUES  ('test', 'testing123');

